# Tentukan versi docker-compose yang digunakan
version: '3.8'

# Definisikan semua layanan (kontainer) yang akan dijalankan
services:
  # Layanan untuk aplikasi NestJS Anda
  app:
    build: .
    container_name: nestjs_app
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    depends_on:
      - mysql
      - redis # Tambahkan kembali dependensi ke redis
    networks:
      - app-network

  # Layanan untuk Redis lokal
  redis:
    image: 'redis:alpine'
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - app-network

  # Layanan untuk MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      # Sesuaikan dengan nama database dari DATABASE_URL Anda
      MYSQL_DATABASE: test-nestjs
      # Password untuk user 'root'
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      # Mapping port 3306 jika Anda perlu mengakses dari luar docker
      - '3306:3306'
    volumes:
      # Di sinilah data MySQL akan disimpan secara permanen
      - db-data:/var/lib/mysql
    networks:
      - app-network

  # Layanan untuk phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql # Menunjuk ke service mysql
      PMA_PORT: 3306
    depends_on:
      - mysql # Harus jalan setelah mysql siap
    networks:
      - app-network

# Definisikan jaringan yang akan digunakan oleh layanan
networks:
  app-network:
    driver: bridge

# Definisikan volume untuk persistensi data
volumes:
  db-data:
    driver: local
